package com.marzia.webserver.dao.model;

import java.io.Serializable;
import java.util.Date;

public class PatientVisit implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientvisit.casenumber
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    private Integer casenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientvisit.diagnose
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    private String diagnose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientvisit.symtoms
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    private String symtoms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientvisit.medicine
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    private String medicine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientvisit.medicinenumber
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    private String medicinenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientvisit.image
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientvisit.image1
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    private String image1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientvisit.image2
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    private String image2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientvisit.image3
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    private String image3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientvisit.visitdate
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    private Date visitdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patientvisit
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientvisit.casenumber
     *
     * @return the value of patientvisit.casenumber
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public Integer getCasenumber() {
        return casenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientvisit.casenumber
     *
     * @param casenumber the value for patientvisit.casenumber
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public void setCasenumber(Integer casenumber) {
        this.casenumber = casenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientvisit.diagnose
     *
     * @return the value of patientvisit.diagnose
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public String getDiagnose() {
        return diagnose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientvisit.diagnose
     *
     * @param diagnose the value for patientvisit.diagnose
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public void setDiagnose(String diagnose) {
        this.diagnose = diagnose == null ? null : diagnose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientvisit.symtoms
     *
     * @return the value of patientvisit.symtoms
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public String getSymtoms() {
        return symtoms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientvisit.symtoms
     *
     * @param symtoms the value for patientvisit.symtoms
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public void setSymtoms(String symtoms) {
        this.symtoms = symtoms == null ? null : symtoms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientvisit.medicine
     *
     * @return the value of patientvisit.medicine
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public String getMedicine() {
        return medicine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientvisit.medicine
     *
     * @param medicine the value for patientvisit.medicine
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public void setMedicine(String medicine) {
        this.medicine = medicine == null ? null : medicine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientvisit.medicinenumber
     *
     * @return the value of patientvisit.medicinenumber
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public String getMedicinenumber() {
        return medicinenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientvisit.medicinenumber
     *
     * @param medicinenumber the value for patientvisit.medicinenumber
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public void setMedicinenumber(String medicinenumber) {
        this.medicinenumber = medicinenumber == null ? null : medicinenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientvisit.image
     *
     * @return the value of patientvisit.image
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientvisit.image
     *
     * @param image the value for patientvisit.image
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientvisit.image1
     *
     * @return the value of patientvisit.image1
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public String getImage1() {
        return image1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientvisit.image1
     *
     * @param image1 the value for patientvisit.image1
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public void setImage1(String image1) {
        this.image1 = image1 == null ? null : image1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientvisit.image2
     *
     * @return the value of patientvisit.image2
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public String getImage2() {
        return image2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientvisit.image2
     *
     * @param image2 the value for patientvisit.image2
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public void setImage2(String image2) {
        this.image2 = image2 == null ? null : image2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientvisit.image3
     *
     * @return the value of patientvisit.image3
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public String getImage3() {
        return image3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientvisit.image3
     *
     * @param image3 the value for patientvisit.image3
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public void setImage3(String image3) {
        this.image3 = image3 == null ? null : image3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientvisit.visitdate
     *
     * @return the value of patientvisit.visitdate
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public Date getVisitdate() {
        return visitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientvisit.visitdate
     *
     * @param visitdate the value for patientvisit.visitdate
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    public void setVisitdate(Date visitdate) {
        this.visitdate = visitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", casenumber=").append(casenumber);
        sb.append(", diagnose=").append(diagnose);
        sb.append(", symtoms=").append(symtoms);
        sb.append(", medicine=").append(medicine);
        sb.append(", medicinenumber=").append(medicinenumber);
        sb.append(", image=").append(image);
        sb.append(", image1=").append(image1);
        sb.append(", image2=").append(image2);
        sb.append(", image3=").append(image3);
        sb.append(", visitdate=").append(visitdate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}