package com.marzia.webserver.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PatientvisitExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    public PatientvisitExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCasenumberIsNull() {
            addCriterion("casenumber is null");
            return (Criteria) this;
        }

        public Criteria andCasenumberIsNotNull() {
            addCriterion("casenumber is not null");
            return (Criteria) this;
        }

        public Criteria andCasenumberEqualTo(Integer value) {
            addCriterion("casenumber =", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotEqualTo(Integer value) {
            addCriterion("casenumber <>", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberGreaterThan(Integer value) {
            addCriterion("casenumber >", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("casenumber >=", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberLessThan(Integer value) {
            addCriterion("casenumber <", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberLessThanOrEqualTo(Integer value) {
            addCriterion("casenumber <=", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberIn(List<Integer> values) {
            addCriterion("casenumber in", values, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotIn(List<Integer> values) {
            addCriterion("casenumber not in", values, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberBetween(Integer value1, Integer value2) {
            addCriterion("casenumber between", value1, value2, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotBetween(Integer value1, Integer value2) {
            addCriterion("casenumber not between", value1, value2, "casenumber");
            return (Criteria) this;
        }

        public Criteria andDiagnoseIsNull() {
            addCriterion("diagnose is null");
            return (Criteria) this;
        }

        public Criteria andDiagnoseIsNotNull() {
            addCriterion("diagnose is not null");
            return (Criteria) this;
        }

        public Criteria andDiagnoseEqualTo(String value) {
            addCriterion("diagnose =", value, "diagnose");
            return (Criteria) this;
        }

        public Criteria andDiagnoseNotEqualTo(String value) {
            addCriterion("diagnose <>", value, "diagnose");
            return (Criteria) this;
        }

        public Criteria andDiagnoseGreaterThan(String value) {
            addCriterion("diagnose >", value, "diagnose");
            return (Criteria) this;
        }

        public Criteria andDiagnoseGreaterThanOrEqualTo(String value) {
            addCriterion("diagnose >=", value, "diagnose");
            return (Criteria) this;
        }

        public Criteria andDiagnoseLessThan(String value) {
            addCriterion("diagnose <", value, "diagnose");
            return (Criteria) this;
        }

        public Criteria andDiagnoseLessThanOrEqualTo(String value) {
            addCriterion("diagnose <=", value, "diagnose");
            return (Criteria) this;
        }

        public Criteria andDiagnoseLike(String value) {
            addCriterion("diagnose like", value, "diagnose");
            return (Criteria) this;
        }

        public Criteria andDiagnoseNotLike(String value) {
            addCriterion("diagnose not like", value, "diagnose");
            return (Criteria) this;
        }

        public Criteria andDiagnoseIn(List<String> values) {
            addCriterion("diagnose in", values, "diagnose");
            return (Criteria) this;
        }

        public Criteria andDiagnoseNotIn(List<String> values) {
            addCriterion("diagnose not in", values, "diagnose");
            return (Criteria) this;
        }

        public Criteria andDiagnoseBetween(String value1, String value2) {
            addCriterion("diagnose between", value1, value2, "diagnose");
            return (Criteria) this;
        }

        public Criteria andDiagnoseNotBetween(String value1, String value2) {
            addCriterion("diagnose not between", value1, value2, "diagnose");
            return (Criteria) this;
        }

        public Criteria andSymtomsIsNull() {
            addCriterion("symtoms is null");
            return (Criteria) this;
        }

        public Criteria andSymtomsIsNotNull() {
            addCriterion("symtoms is not null");
            return (Criteria) this;
        }

        public Criteria andSymtomsEqualTo(String value) {
            addCriterion("symtoms =", value, "symtoms");
            return (Criteria) this;
        }

        public Criteria andSymtomsNotEqualTo(String value) {
            addCriterion("symtoms <>", value, "symtoms");
            return (Criteria) this;
        }

        public Criteria andSymtomsGreaterThan(String value) {
            addCriterion("symtoms >", value, "symtoms");
            return (Criteria) this;
        }

        public Criteria andSymtomsGreaterThanOrEqualTo(String value) {
            addCriterion("symtoms >=", value, "symtoms");
            return (Criteria) this;
        }

        public Criteria andSymtomsLessThan(String value) {
            addCriterion("symtoms <", value, "symtoms");
            return (Criteria) this;
        }

        public Criteria andSymtomsLessThanOrEqualTo(String value) {
            addCriterion("symtoms <=", value, "symtoms");
            return (Criteria) this;
        }

        public Criteria andSymtomsLike(String value) {
            addCriterion("symtoms like", value, "symtoms");
            return (Criteria) this;
        }

        public Criteria andSymtomsNotLike(String value) {
            addCriterion("symtoms not like", value, "symtoms");
            return (Criteria) this;
        }

        public Criteria andSymtomsIn(List<String> values) {
            addCriterion("symtoms in", values, "symtoms");
            return (Criteria) this;
        }

        public Criteria andSymtomsNotIn(List<String> values) {
            addCriterion("symtoms not in", values, "symtoms");
            return (Criteria) this;
        }

        public Criteria andSymtomsBetween(String value1, String value2) {
            addCriterion("symtoms between", value1, value2, "symtoms");
            return (Criteria) this;
        }

        public Criteria andSymtomsNotBetween(String value1, String value2) {
            addCriterion("symtoms not between", value1, value2, "symtoms");
            return (Criteria) this;
        }

        public Criteria andMedicineIsNull() {
            addCriterion("medicine is null");
            return (Criteria) this;
        }

        public Criteria andMedicineIsNotNull() {
            addCriterion("medicine is not null");
            return (Criteria) this;
        }

        public Criteria andMedicineEqualTo(String value) {
            addCriterion("medicine =", value, "medicine");
            return (Criteria) this;
        }

        public Criteria andMedicineNotEqualTo(String value) {
            addCriterion("medicine <>", value, "medicine");
            return (Criteria) this;
        }

        public Criteria andMedicineGreaterThan(String value) {
            addCriterion("medicine >", value, "medicine");
            return (Criteria) this;
        }

        public Criteria andMedicineGreaterThanOrEqualTo(String value) {
            addCriterion("medicine >=", value, "medicine");
            return (Criteria) this;
        }

        public Criteria andMedicineLessThan(String value) {
            addCriterion("medicine <", value, "medicine");
            return (Criteria) this;
        }

        public Criteria andMedicineLessThanOrEqualTo(String value) {
            addCriterion("medicine <=", value, "medicine");
            return (Criteria) this;
        }

        public Criteria andMedicineLike(String value) {
            addCriterion("medicine like", value, "medicine");
            return (Criteria) this;
        }

        public Criteria andMedicineNotLike(String value) {
            addCriterion("medicine not like", value, "medicine");
            return (Criteria) this;
        }

        public Criteria andMedicineIn(List<String> values) {
            addCriterion("medicine in", values, "medicine");
            return (Criteria) this;
        }

        public Criteria andMedicineNotIn(List<String> values) {
            addCriterion("medicine not in", values, "medicine");
            return (Criteria) this;
        }

        public Criteria andMedicineBetween(String value1, String value2) {
            addCriterion("medicine between", value1, value2, "medicine");
            return (Criteria) this;
        }

        public Criteria andMedicineNotBetween(String value1, String value2) {
            addCriterion("medicine not between", value1, value2, "medicine");
            return (Criteria) this;
        }

        public Criteria andMedicinenumberIsNull() {
            addCriterion("medicinenumber is null");
            return (Criteria) this;
        }

        public Criteria andMedicinenumberIsNotNull() {
            addCriterion("medicinenumber is not null");
            return (Criteria) this;
        }

        public Criteria andMedicinenumberEqualTo(String value) {
            addCriterion("medicinenumber =", value, "medicinenumber");
            return (Criteria) this;
        }

        public Criteria andMedicinenumberNotEqualTo(String value) {
            addCriterion("medicinenumber <>", value, "medicinenumber");
            return (Criteria) this;
        }

        public Criteria andMedicinenumberGreaterThan(String value) {
            addCriterion("medicinenumber >", value, "medicinenumber");
            return (Criteria) this;
        }

        public Criteria andMedicinenumberGreaterThanOrEqualTo(String value) {
            addCriterion("medicinenumber >=", value, "medicinenumber");
            return (Criteria) this;
        }

        public Criteria andMedicinenumberLessThan(String value) {
            addCriterion("medicinenumber <", value, "medicinenumber");
            return (Criteria) this;
        }

        public Criteria andMedicinenumberLessThanOrEqualTo(String value) {
            addCriterion("medicinenumber <=", value, "medicinenumber");
            return (Criteria) this;
        }

        public Criteria andMedicinenumberLike(String value) {
            addCriterion("medicinenumber like", value, "medicinenumber");
            return (Criteria) this;
        }

        public Criteria andMedicinenumberNotLike(String value) {
            addCriterion("medicinenumber not like", value, "medicinenumber");
            return (Criteria) this;
        }

        public Criteria andMedicinenumberIn(List<String> values) {
            addCriterion("medicinenumber in", values, "medicinenumber");
            return (Criteria) this;
        }

        public Criteria andMedicinenumberNotIn(List<String> values) {
            addCriterion("medicinenumber not in", values, "medicinenumber");
            return (Criteria) this;
        }

        public Criteria andMedicinenumberBetween(String value1, String value2) {
            addCriterion("medicinenumber between", value1, value2, "medicinenumber");
            return (Criteria) this;
        }

        public Criteria andMedicinenumberNotBetween(String value1, String value2) {
            addCriterion("medicinenumber not between", value1, value2, "medicinenumber");
            return (Criteria) this;
        }

        public Criteria andImageIsNull() {
            addCriterion("image is null");
            return (Criteria) this;
        }

        public Criteria andImageIsNotNull() {
            addCriterion("image is not null");
            return (Criteria) this;
        }

        public Criteria andImageEqualTo(String value) {
            addCriterion("image =", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotEqualTo(String value) {
            addCriterion("image <>", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThan(String value) {
            addCriterion("image >", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThanOrEqualTo(String value) {
            addCriterion("image >=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThan(String value) {
            addCriterion("image <", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThanOrEqualTo(String value) {
            addCriterion("image <=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLike(String value) {
            addCriterion("image like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotLike(String value) {
            addCriterion("image not like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageIn(List<String> values) {
            addCriterion("image in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotIn(List<String> values) {
            addCriterion("image not in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageBetween(String value1, String value2) {
            addCriterion("image between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotBetween(String value1, String value2) {
            addCriterion("image not between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andImage1IsNull() {
            addCriterion("image1 is null");
            return (Criteria) this;
        }

        public Criteria andImage1IsNotNull() {
            addCriterion("image1 is not null");
            return (Criteria) this;
        }

        public Criteria andImage1EqualTo(String value) {
            addCriterion("image1 =", value, "image1");
            return (Criteria) this;
        }

        public Criteria andImage1NotEqualTo(String value) {
            addCriterion("image1 <>", value, "image1");
            return (Criteria) this;
        }

        public Criteria andImage1GreaterThan(String value) {
            addCriterion("image1 >", value, "image1");
            return (Criteria) this;
        }

        public Criteria andImage1GreaterThanOrEqualTo(String value) {
            addCriterion("image1 >=", value, "image1");
            return (Criteria) this;
        }

        public Criteria andImage1LessThan(String value) {
            addCriterion("image1 <", value, "image1");
            return (Criteria) this;
        }

        public Criteria andImage1LessThanOrEqualTo(String value) {
            addCriterion("image1 <=", value, "image1");
            return (Criteria) this;
        }

        public Criteria andImage1Like(String value) {
            addCriterion("image1 like", value, "image1");
            return (Criteria) this;
        }

        public Criteria andImage1NotLike(String value) {
            addCriterion("image1 not like", value, "image1");
            return (Criteria) this;
        }

        public Criteria andImage1In(List<String> values) {
            addCriterion("image1 in", values, "image1");
            return (Criteria) this;
        }

        public Criteria andImage1NotIn(List<String> values) {
            addCriterion("image1 not in", values, "image1");
            return (Criteria) this;
        }

        public Criteria andImage1Between(String value1, String value2) {
            addCriterion("image1 between", value1, value2, "image1");
            return (Criteria) this;
        }

        public Criteria andImage1NotBetween(String value1, String value2) {
            addCriterion("image1 not between", value1, value2, "image1");
            return (Criteria) this;
        }

        public Criteria andImage2IsNull() {
            addCriterion("image2 is null");
            return (Criteria) this;
        }

        public Criteria andImage2IsNotNull() {
            addCriterion("image2 is not null");
            return (Criteria) this;
        }

        public Criteria andImage2EqualTo(String value) {
            addCriterion("image2 =", value, "image2");
            return (Criteria) this;
        }

        public Criteria andImage2NotEqualTo(String value) {
            addCriterion("image2 <>", value, "image2");
            return (Criteria) this;
        }

        public Criteria andImage2GreaterThan(String value) {
            addCriterion("image2 >", value, "image2");
            return (Criteria) this;
        }

        public Criteria andImage2GreaterThanOrEqualTo(String value) {
            addCriterion("image2 >=", value, "image2");
            return (Criteria) this;
        }

        public Criteria andImage2LessThan(String value) {
            addCriterion("image2 <", value, "image2");
            return (Criteria) this;
        }

        public Criteria andImage2LessThanOrEqualTo(String value) {
            addCriterion("image2 <=", value, "image2");
            return (Criteria) this;
        }

        public Criteria andImage2Like(String value) {
            addCriterion("image2 like", value, "image2");
            return (Criteria) this;
        }

        public Criteria andImage2NotLike(String value) {
            addCriterion("image2 not like", value, "image2");
            return (Criteria) this;
        }

        public Criteria andImage2In(List<String> values) {
            addCriterion("image2 in", values, "image2");
            return (Criteria) this;
        }

        public Criteria andImage2NotIn(List<String> values) {
            addCriterion("image2 not in", values, "image2");
            return (Criteria) this;
        }

        public Criteria andImage2Between(String value1, String value2) {
            addCriterion("image2 between", value1, value2, "image2");
            return (Criteria) this;
        }

        public Criteria andImage2NotBetween(String value1, String value2) {
            addCriterion("image2 not between", value1, value2, "image2");
            return (Criteria) this;
        }

        public Criteria andImage3IsNull() {
            addCriterion("image3 is null");
            return (Criteria) this;
        }

        public Criteria andImage3IsNotNull() {
            addCriterion("image3 is not null");
            return (Criteria) this;
        }

        public Criteria andImage3EqualTo(String value) {
            addCriterion("image3 =", value, "image3");
            return (Criteria) this;
        }

        public Criteria andImage3NotEqualTo(String value) {
            addCriterion("image3 <>", value, "image3");
            return (Criteria) this;
        }

        public Criteria andImage3GreaterThan(String value) {
            addCriterion("image3 >", value, "image3");
            return (Criteria) this;
        }

        public Criteria andImage3GreaterThanOrEqualTo(String value) {
            addCriterion("image3 >=", value, "image3");
            return (Criteria) this;
        }

        public Criteria andImage3LessThan(String value) {
            addCriterion("image3 <", value, "image3");
            return (Criteria) this;
        }

        public Criteria andImage3LessThanOrEqualTo(String value) {
            addCriterion("image3 <=", value, "image3");
            return (Criteria) this;
        }

        public Criteria andImage3Like(String value) {
            addCriterion("image3 like", value, "image3");
            return (Criteria) this;
        }

        public Criteria andImage3NotLike(String value) {
            addCriterion("image3 not like", value, "image3");
            return (Criteria) this;
        }

        public Criteria andImage3In(List<String> values) {
            addCriterion("image3 in", values, "image3");
            return (Criteria) this;
        }

        public Criteria andImage3NotIn(List<String> values) {
            addCriterion("image3 not in", values, "image3");
            return (Criteria) this;
        }

        public Criteria andImage3Between(String value1, String value2) {
            addCriterion("image3 between", value1, value2, "image3");
            return (Criteria) this;
        }

        public Criteria andImage3NotBetween(String value1, String value2) {
            addCriterion("image3 not between", value1, value2, "image3");
            return (Criteria) this;
        }

        public Criteria andVisitdateIsNull() {
            addCriterion("visitdate is null");
            return (Criteria) this;
        }

        public Criteria andVisitdateIsNotNull() {
            addCriterion("visitdate is not null");
            return (Criteria) this;
        }

        public Criteria andVisitdateEqualTo(Date value) {
            addCriterion("visitdate =", value, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateNotEqualTo(Date value) {
            addCriterion("visitdate <>", value, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateGreaterThan(Date value) {
            addCriterion("visitdate >", value, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateGreaterThanOrEqualTo(Date value) {
            addCriterion("visitdate >=", value, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateLessThan(Date value) {
            addCriterion("visitdate <", value, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateLessThanOrEqualTo(Date value) {
            addCriterion("visitdate <=", value, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateIn(List<Date> values) {
            addCriterion("visitdate in", values, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateNotIn(List<Date> values) {
            addCriterion("visitdate not in", values, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateBetween(Date value1, Date value2) {
            addCriterion("visitdate between", value1, value2, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateNotBetween(Date value1, Date value2) {
            addCriterion("visitdate not between", value1, value2, "visitdate");
            return (Criteria) this;
        }

        public Criteria andDiagnoseLikeInsensitive(String value) {
            addCriterion("upper(diagnose) like", value.toUpperCase(), "diagnose");
            return (Criteria) this;
        }

        public Criteria andSymtomsLikeInsensitive(String value) {
            addCriterion("upper(symtoms) like", value.toUpperCase(), "symtoms");
            return (Criteria) this;
        }

        public Criteria andMedicineLikeInsensitive(String value) {
            addCriterion("upper(medicine) like", value.toUpperCase(), "medicine");
            return (Criteria) this;
        }

        public Criteria andMedicinenumberLikeInsensitive(String value) {
            addCriterion("upper(medicinenumber) like", value.toUpperCase(), "medicinenumber");
            return (Criteria) this;
        }

        public Criteria andImageLikeInsensitive(String value) {
            addCriterion("upper(image) like", value.toUpperCase(), "image");
            return (Criteria) this;
        }

        public Criteria andImage1LikeInsensitive(String value) {
            addCriterion("upper(image1) like", value.toUpperCase(), "image1");
            return (Criteria) this;
        }

        public Criteria andImage2LikeInsensitive(String value) {
            addCriterion("upper(image2) like", value.toUpperCase(), "image2");
            return (Criteria) this;
        }

        public Criteria andImage3LikeInsensitive(String value) {
            addCriterion("upper(image3) like", value.toUpperCase(), "image3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patientvisit
     *
     * @mbg.generated do_not_delete_during_merge Thu May 09 13:51:04 EDT 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}