package com.marzia.webserver.dao.repository;

import com.marzia.webserver.dao.model.Patients;
import com.marzia.webserver.dao.model.PatientsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatientsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patients
     *
     * @mbg.generated Thu May 09 16:23:43 EDT 2019
     */
    int deleteByExample(PatientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patients
     *
     * @mbg.generated Thu May 09 16:23:43 EDT 2019
     */
    int deleteByPrimaryKey(Integer casenumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patients
     *
     * @mbg.generated Thu May 09 16:23:43 EDT 2019
     */
    int insert(Patients record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patients
     *
     * @mbg.generated Thu May 09 16:23:43 EDT 2019
     */
    int insertSelective(Patients record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patients
     *
     * @mbg.generated Thu May 09 16:23:43 EDT 2019
     */
    List<Patients> selectByExample(PatientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patients
     *
     * @mbg.generated Thu May 09 16:23:43 EDT 2019
     */
    Patients selectByPrimaryKey(Integer casenumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patients
     *
     * @mbg.generated Thu May 09 16:23:43 EDT 2019
     */
    int updateByExampleSelective(@Param("record") Patients record, @Param("example") PatientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patients
     *
     * @mbg.generated Thu May 09 16:23:43 EDT 2019
     */
    int updateByExample(@Param("record") Patients record, @Param("example") PatientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patients
     *
     * @mbg.generated Thu May 09 16:23:43 EDT 2019
     */
    int updateByPrimaryKeySelective(Patients record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patients
     *
     * @mbg.generated Thu May 09 16:23:43 EDT 2019
     */
    int updateByPrimaryKey(Patients record);
}