package com.marzia.webserver.dao.repository;

import com.marzia.webserver.dao.model.PatientVisit;
import com.marzia.webserver.dao.model.PatientVisitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatientVisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Tue Jun 11 13:44:19 EDT 2019
     */
    int deleteByExample(PatientVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Tue Jun 11 13:44:19 EDT 2019
     */
    int insert(PatientVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Tue Jun 11 13:44:19 EDT 2019
     */
    int insertSelective(PatientVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Tue Jun 11 13:44:19 EDT 2019
     */
    List<PatientVisit> selectByExample(PatientVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Tue Jun 11 13:44:19 EDT 2019
     */
    int updateByExampleSelective(@Param("record") PatientVisit record, @Param("example") PatientVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Tue Jun 11 13:44:19 EDT 2019
     */
    int updateByExample(@Param("record") PatientVisit record, @Param("example") PatientVisitExample example);
}