package com.marzia.webserver.dao.repository;

import com.marzia.webserver.dao.model.Patientvisit;
import com.marzia.webserver.dao.model.PatientvisitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatientvisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    int deleteByExample(PatientvisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    int insert(Patientvisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    int insertSelective(Patientvisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    List<Patientvisit> selectByExample(PatientvisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    int updateByExampleSelective(@Param("record") Patientvisit record, @Param("example") PatientvisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientvisit
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    int updateByExample(@Param("record") Patientvisit record, @Param("example") PatientvisitExample example);
}