package com.marzia.webserver.dao.repository;

import com.marzia.webserver.dao.model.RateBook;
import com.marzia.webserver.dao.model.RateBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RateBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Tue Jun 11 13:44:19 EDT 2019
     */
    int deleteByExample(RateBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Tue Jun 11 13:44:19 EDT 2019
     */
    int deleteByPrimaryKey(Integer sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Tue Jun 11 13:44:19 EDT 2019
     */
    int insert(RateBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Tue Jun 11 13:44:19 EDT 2019
     */
    int insertSelective(RateBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Tue Jun 11 13:44:19 EDT 2019
     */
    List<RateBook> selectByExample(RateBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Tue Jun 11 13:44:19 EDT 2019
     */
    RateBook selectByPrimaryKey(Integer sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Tue Jun 11 13:44:19 EDT 2019
     */
    int updateByExampleSelective(@Param("record") RateBook record, @Param("example") RateBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Tue Jun 11 13:44:19 EDT 2019
     */
    int updateByExample(@Param("record") RateBook record, @Param("example") RateBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Tue Jun 11 13:44:19 EDT 2019
     */
    int updateByPrimaryKeySelective(RateBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Tue Jun 11 13:44:19 EDT 2019
     */
    int updateByPrimaryKey(RateBook record);
}