package com.marzia.webserver.dao.repository;

import com.marzia.webserver.dao.model.Ratebook;
import com.marzia.webserver.dao.model.RatebookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RatebookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    int deleteByExample(RatebookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    int deleteByPrimaryKey(Integer sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    int insert(Ratebook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    int insertSelective(Ratebook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    List<Ratebook> selectByExample(RatebookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    Ratebook selectByPrimaryKey(Integer sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    int updateByExampleSelective(@Param("record") Ratebook record, @Param("example") RatebookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    int updateByExample(@Param("record") Ratebook record, @Param("example") RatebookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    int updateByPrimaryKeySelective(Ratebook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratebook
     *
     * @mbg.generated Thu May 09 13:51:04 EDT 2019
     */
    int updateByPrimaryKey(Ratebook record);
}