package com.marzia.webserver.dao.repository;

import com.marzia.webserver.dao.model.UserRoles;
import com.marzia.webserver.dao.model.UserRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRolesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_roles
	 * @mbg.generated  Sun Oct 21 17:18:00 EDT 2018
	 */
	int deleteByExample(UserRolesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_roles
	 * @mbg.generated  Sun Oct 21 17:18:00 EDT 2018
	 */
	int deleteByPrimaryKey(Integer userRoleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_roles
	 * @mbg.generated  Sun Oct 21 17:18:00 EDT 2018
	 */
	int insert(UserRoles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_roles
	 * @mbg.generated  Sun Oct 21 17:18:00 EDT 2018
	 */
	int insertSelective(UserRoles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_roles
	 * @mbg.generated  Sun Oct 21 17:18:00 EDT 2018
	 */
	List<UserRoles> selectByExample(UserRolesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_roles
	 * @mbg.generated  Sun Oct 21 17:18:00 EDT 2018
	 */
	UserRoles selectByPrimaryKey(Integer userRoleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_roles
	 * @mbg.generated  Sun Oct 21 17:18:00 EDT 2018
	 */
	int updateByExampleSelective(@Param("record") UserRoles record, @Param("example") UserRolesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_roles
	 * @mbg.generated  Sun Oct 21 17:18:00 EDT 2018
	 */
	int updateByExample(@Param("record") UserRoles record, @Param("example") UserRolesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_roles
	 * @mbg.generated  Sun Oct 21 17:18:00 EDT 2018
	 */
	int updateByPrimaryKeySelective(UserRoles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_roles
	 * @mbg.generated  Sun Oct 21 17:18:00 EDT 2018
	 */
	int updateByPrimaryKey(UserRoles record);
}