package com.marzia.webserver.dao.repository;

import com.marzia.webserver.dao.model.UserRoles;
import com.marzia.webserver.dao.model.UserRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    int deleteByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    int deleteByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    int insert(UserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    int insertSelective(UserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    List<UserRoles> selectByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    UserRoles selectByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    int updateByExampleSelective(@Param("record") UserRoles record, @Param("example") UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    int updateByExample(@Param("record") UserRoles record, @Param("example") UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    int updateByPrimaryKeySelective(UserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Tue Jul 02 11:26:47 EDT 2019
     */
    int updateByPrimaryKey(UserRoles record);
}